// <auto-generated />
using HotelForDogs.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelForDogs.Migrations
{
    [DbContext(typeof(ClientContext))]
    partial class ClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelForDogs.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("DogId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            DogId = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PhoneNumber = "505505505"
                        },
                        new
                        {
                            ClientId = 2,
                            DogId = 2,
                            FirstName = "Jan",
                            LastName = "Nowak",
                            PhoneNumber = "606606606"
                        },
                        new
                        {
                            ClientId = 3,
                            DogId = 3,
                            FirstName = "John",
                            LastName = "Smith",
                            PhoneNumber = "707707707"
                        });
                });

            modelBuilder.Entity("HotelForDogs.Entities.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Breed = "Crossbreed",
                            Name = "Rex",
                            Weight = 15
                        },
                        new
                        {
                            DogId = 2,
                            Breed = "Basset",
                            Name = "Max",
                            Weight = 8
                        },
                        new
                        {
                            DogId = 3,
                            Breed = "Colli",
                            Name = "Fred",
                            Weight = 36
                        });
                });

            modelBuilder.Entity("HotelForDogs.Entities.Client", b =>
                {
                    b.HasOne("HotelForDogs.Entities.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });
#pragma warning restore 612, 618
        }
    }
}
